export const movies = [
  {
    movie_id: 1,
    title: "Spider-Man: Homecoming",
    overview: "Following the events of Captain America: Civil War.",
    release_date: "2017-07-05",
    poster_path: "/ApYhuwBWzl29Oxe9JJsgL7qILbD.jpg",
    backdrop_path: "/tPpYGm2mVecue7Bk3gNVoSPA5qn.jpg",
    vote_average: 7.4,
  },
  {
    movie_id: 2,
    title: "Spider-Man: Homecoming",
    overview: "Following the events of Captain America: Civil War.",
    release_date: "2017-07-05",
    poster_path: "/ApYhuwBWzl29Oxe9JJsgL7qILbD.jpg",
    backdrop_path: "/tPpYGm2mVecue7Bk3gNVoSPA5qn.jpg",
    vote_average: 7.4,
  },
  {
    movie_id: 3,
    title: "Spider-Man: Homecoming",
    overview: "Following the events of Captain America: Civil War.",
    release_date: "2017-07-05",
    poster_path: "/ApYhuwBWzl29Oxe9JJsgL7qILbD.jpg",
    backdrop_path: "/tPpYGm2mVecue7Bk3gNVoSPA5qn.jpg",
    vote_average: 7.4,
  },
  {
    movie_id: 4,
    title: "Spider-Man: Homecoming",
    overview: "Following the events of Captain America: Civil War.",
    release_date: "2017-07-05",
    poster_path: "/ApYhuwBWzl29Oxe9JJsgL7qILbD.jpg",
    backdrop_path: "/tPpYGm2mVecue7Bk3gNVoSPA5qn.jpg",
    vote_average: 7.4,
  },
  {
    movie_id: 5,
    title: "Spider-Man: Homecoming",
    overview: "Following the events of Captain America: Civil War.",
    release_date: "2017-07-05",
    poster_path: "/ApYhuwBWzl29Oxe9JJsgL7qILbD.jpg",
    backdrop_path: "/tPpYGm2mVecue7Bk3gNVoSPA5qn.jpg",
    vote_average: 7.4,
  },
  {
    movie_id: 6,
    title: "Spider-Man: Homecoming",
    overview: "Following the events of Captain America: Civil War.",
    release_date: "2017-07-05",
    poster_path: "/ApYhuwBWzl29Oxe9JJsgL7qILbD.jpg",
    backdrop_path: "/tPpYGm2mVecue7Bk3gNVoSPA5qn.jpg",
    vote_average: 7.4,
  },
  {
    movie_id: 7,
    title: "Spider-Man: Homecoming",
    overview: "Following the events of Captain America: Civil War.",
    release_date: "2017-07-05",
    poster_path: "/ApYhuwBWzl29Oxe9JJsgL7qILbD.jpg",
    backdrop_path: "/tPpYGm2mVecue7Bk3gNVoSPA5qn.jpg",
    vote_average: 7.4,
  },
  {
    movie_id: 8,
    title: "Spider-Man: Homecoming",
    overview: "Following the events of Captain America: Civil War.",
    release_date: "2017-07-05",
    poster_path: "/ApYhuwBWzl29Oxe9JJsgL7qILbD.jpg",
    backdrop_path: "/tPpYGm2mVecue7Bk3gNVoSPA5qn.jpg",
    vote_average: 7.4,
  },
  {
    movie_id: 9,
    title: "Spider-Man: Homecoming",
    overview: "Following the events of Captain America: Civil War.",
    release_date: "2017-07-05",
    poster_path: "/ApYhuwBWzl29Oxe9JJsgL7qILbD.jpg",
    backdrop_path: "/tPpYGm2mVecue7Bk3gNVoSPA5qn.jpg",
    vote_average: 7.4,
  },
  {
    movie_id: 10,
    title: "Spider-Man: Homecoming",
    overview: "Following the events of Captain America: Civil War.",
    release_date: "2017-07-05",
    poster_path: "/ApYhuwBWzl29Oxe9JJsgL7qILbD.jpg",
    backdrop_path: "/tPpYGm2mVecue7Bk3gNVoSPA5qn.jpg",
    vote_average: 7.4,
  },
  {
    movie_id: 11,
    title: "Spider-Man: Homecoming",
    overview: "Following the events of Captain America: Civil War.",
    release_date: "2017-07-05",
    poster_path: "/ApYhuwBWzl29Oxe9JJsgL7qILbD.jpg",
    backdrop_path: "/tPpYGm2mVecue7Bk3gNVoSPA5qn.jpg",
    vote_average: 7.4,
  },
  {
    movie_id: 12,
    title: "Spider-Man: Homecoming",
    overview: "Following the events of Captain America: Civil War.",
    release_date: "2017-07-05",
    poster_path: "/ApYhuwBWzl29Oxe9JJsgL7qILbD.jpg",
    backdrop_path: "/tPpYGm2mVecue7Bk3gNVoSPA5qn.jpg",
    vote_average: 7.4,
  },
  {
    movie_id: 13,
    title: "Spider-Man: Homecoming",
    overview: "Following the events of Captain America: Civil War.",
    release_date: "2017-07-05",
    poster_path: "/ApYhuwBWzl29Oxe9JJsgL7qILbD.jpg",
    backdrop_path: "/tPpYGm2mVecue7Bk3gNVoSPA5qn.jpg",
    vote_average: 7.4,
  },
  {
    movie_id: 14,
    title: "Spider-Man: Homecoming",
    overview: "Following the events of Captain America: Civil War.",
    release_date: "2017-07-05",
    poster_path: "/ApYhuwBWzl29Oxe9JJsgL7qILbD.jpg",
    backdrop_path: "/tPpYGm2mVecue7Bk3gNVoSPA5qn.jpg",
    vote_average: 7.4,
  },
  {
    movie_id: 15,
    title: "Spider-Man: Homecoming",
    overview: "Following the events of Captain America: Civil War.",
    release_date: "2017-07-05",
    poster_path: "/ApYhuwBWzl29Oxe9JJsgL7qILbD.jpg",
    backdrop_path: "/tPpYGm2mVecue7Bk3gNVoSPA5qn.jpg",
    vote_average: 7.4,
  },
  {
    movie_id: 16,
    title: "Spider-Man: Homecoming",
    overview: "Following the events of Captain America: Civil War.",
    release_date: "2017-07-05",
    poster_path: "/ApYhuwBWzl29Oxe9JJsgL7qILbD.jpg",
    backdrop_path: "/tPpYGm2mVecue7Bk3gNVoSPA5qn.jpg",
    vote_average: 7.4,
  },
  {
    movie_id: 17,
    title: "Spider-Man: Homecoming",
    overview: "Following the events of Captain America: Civil War.",
    release_date: "2017-07-05",
    poster_path: "/ApYhuwBWzl29Oxe9JJsgL7qILbD.jpg",
    backdrop_path: "/tPpYGm2mVecue7Bk3gNVoSPA5qn.jpg",
    vote_average: 7.4,
  },
  {
    movie_id: 18,
    title: "Spider-Man: Homecoming",
    overview: "Following the events of Captain America: Civil War.",
    release_date: "2017-07-05",
    poster_path: "/ApYhuwBWzl29Oxe9JJsgL7qILbD.jpg",
    backdrop_path: "/tPpYGm2mVecue7Bk3gNVoSPA5qn.jpg",
    vote_average: 7.4,
  },
  {
    movie_id: 19,
    title: "Spider-Man: Homecoming",
    overview: "Following the events of Captain America: Civil War.",
    release_date: "2017-07-05",
    poster_path: "/ApYhuwBWzl29Oxe9JJsgL7qILbD.jpg",
    backdrop_path: "/tPpYGm2mVecue7Bk3gNVoSPA5qn.jpg",
    vote_average: 7.4,
  },
  {
    movie_id: 20,
    title: "Spider-Man: Homecoming",
    overview: "Following the events of Captain America: Civil War.",
    release_date: "2017-07-05",
    poster_path: "/ApYhuwBWzl29Oxe9JJsgL7qILbD.jpg",
    backdrop_path: "/tPpYGm2mVecue7Bk3gNVoSPA5qn.jpg",
    vote_average: 7.4,
  },
];
